### ISSUE TITLE
clean-css upgrade request

### ISSUE THREAD

**Issue by ghost** [magnars/optimus#63]
thanks for writing optimus!
It would be nice if the clean-css dependency could be upgraded to the latest version, as it contains some bugfixes regarding attribute merging etc.

**Comment by magnars** [comment]
Thanks for the heads up, @sj4 - that's a good idea. Could you give me one CSS-example for one such bug fix (before and after), so that I can add it to the test suite and verify that I've done the upgrade correctly? 🙂

**Comment by sj4** [comment]
before upgrade, with clean-css 3.0.7, the following input css 
```css
.app-logo {
  background: url('/og.png') no-repeat center;
  background-color: none;
}
```

will result in 
```css
.app-logo{background:url(/og.png) center no-repeat none}
```
which is wrong.

a later version of clean-css should *not* merge `background-color: none;` into `background`
